import "@/styles/globals.css";
import { Almarai, El_Messiri } from "next/font/google"


const primaryFont = Almarai({
  subsets: ["arabic"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-primary",
  fallback: ["san-serif"]
})

const secondaryFont = El_Messiri({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-secondary",
  fallback: ["san-serif"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  author: "Alireza Ghanbari"
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" >
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable}
        font-primary antialiased   bg-theme`}
      >
        {children}
      </body>
    </html>
  );
}
