import "@/styles/globals.css";
import { Almarai, El_Messiri } from "next/font/google"
import Header from "@/components/templates/home/Header";
import Navbar from "@/components/templates/home/Navbar";
import Footer from "@/components/templates/home/Footer";

const primaryFont = Almarai({
  subsets: ["arabic"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-primary",
  fallback: ["san-serif"]
})

const secondaryFont = El_Messiri({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-secondary",
  fallback: ["san-serif"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  author: "Alireza Ghanbari"
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" >
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} font-primary bg-theme flex flex-col min-h-svh justify-between antialiased`}
      >
        <div>
          <Header />
          <Navbar />
          <div className="container my-2">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
